image: debian/stable
packages:
  - ruby
  - ruby-bundler
  - ruby-dev
  - libyaml-dev
  - git
  - postgresql
  - libpq-dev
sources:
  - https://git.sr.ht/~czan/active_record_rules
tasks:
  - deps: |
      cd active_record_rules
      bundle config set --local path 'gems'
      bundle install
  - lint: |
      cd active_record_rules
      bundle exec rubocop
  - sqlite-test: |
      cd active_record_rules
      bundle exec rake spec
  - postgres-test: |
      cd active_record_rules
      sudo -u postgres createuser active_record_rules
      export ARR_DATABASE="postgres:///active_record_rules?host=/var/run/postgresql"
      sudo -Eu postgres bundle exec rspec
