AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/NumberedParametersLimit:
  Enabled: true
  Max: 2

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Max: 120
