require:
  - 'rubocop-rspec'

plugins:
  - 'rubocop-capybara'

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  Include:
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
  Exclude:
    - 'vendor/**/*'
    - 'gems/**/*'

Style/Documentation:
  Enabled: false

Style/ArgumentsForwarding:
  # I'm getting errors about this in CI, despite the fact that our
  # TargetRubyVersion is 3.0 (where this syntax is not allowed).
  Enabled: false

# Disable all the cops about length/complexity, because they're pretty
# noisy.
Metrics:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

# This is particularly useful for mapping over hashes. I don't think
# _1 and _2 is too confusing, but adding _3 starts to push it.
Style/NumberedParametersLimit:
  Enabled: true
  Max: 2

Layout/LineLength:
  Max: 120

RSpec/NestedGroups:
  Max: 4

# This is a style issue that I don't care about. Sometimes indexes are
# meaningful enough!
RSpec/IndexedLet:
  Enabled: false
