require:
  - 'rubocop-rspec'

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

# Disable all the cops about length/complexity, because they're pretty
# noisy.
Metrics:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/NumberedParametersLimit:
  Enabled: true
  Max: 2

Layout/LineLength:
  Max: 120
