require:
  - 'rubocop-rspec'

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Include:
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'

# Disable all the cops about length/complexity, because they're pretty
# noisy.
Metrics:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

# This is particularly useful for mapping over hashes. I don't think
# _1 and _2 is too confusing, but adding _3 starts to push it.
Style/NumberedParametersLimit:
  Enabled: true
  Max: 2

Layout/LineLength:
  Max: 120

RSpec/NestedGroups:
  Max: 4
